"""
Hypothesis Runner (Sweep)
=========================

Automates the discovery of alpha by sweeping through:
1. All features in the Feature Library.
2. A meaningful set of parameters.
3. Universal backtesting via RapidResearchBacktester.

This is the "Search" engine of the Alpha Factory.
"""

import pandas as pd
import numpy as np
import logging
from typing import List, Dict
from itertools import product
from research.rapid_research_backtester import RapidResearchBacktester
from research.hypothesis_manager import HypothesisManager
from features.library import FEATURE_REGISTRY

logger = logging.getLogger(__name__)

class SweepRunner:
    def __init__(self, manager: HypothesisManager, backtester: RapidResearchBacktester):
        self.manager = manager
        self.backtester = backtester

    def run_sweep(self, market_data: pd.DataFrame, top_k: int = 10):
        """
        Run a grid search over features and basic logic.

        Hypothesis Structure Considered:
        "Long if Feature > Threshold", "Short if Feature < Threshold"

        Args:
            market_data: OHLCV DataFrame
            top_k: Number of best hypotheses to log detailed info for (or could log all)
        """
        logger.info(f"Starting Hypothesis Sweep over {len(FEATURE_REGISTRY)} features...")

        results = []

        for feature_name, calc_func in FEATURE_REGISTRY.items():
            try:
                # 1. Calculate Feature
                # Assuming calc_func takes 'Close' or the whole DF?
                # Library currently expects Series (Close)
                if 'Close' not in market_data.columns:
                    continue

                feature_series = calc_func(market_data['Close'])

                # 2. Define standard test variations
                # e.g., Mean Reversion logic (Z-score like) or Trend logic
                # For MVP, let's test a simple "Trend" logic: signal = sign(feature)
                # And "Mean Reversion": signal = -sign(feature)

                # Variation A: Trend
                # Hypothesis: Feature predicts direction
                hyp_name_trend = f"{feature_name}_Trend"
                metrics_trans = self._test_logic(market_data, feature_series, mode='trend')
                self._record_result(hyp_name_trend, metrics_trans)

                # Variation B: Mean Reversion
                hyp_name_mr = f"{feature_name}_MeanRev"
                metrics_mr = self._test_logic(market_data, feature_series, mode='mr')
                self._record_result(hyp_name_mr, metrics_mr)

            except Exception as e:
                logger.error(f"Failed to sweep feature {feature_name}: {e}")

    def _test_logic(self, market_data, feature_series, mode='trend'):

        def signal_logic(data):
            # We use the pre-calculated series, aligned by index
            # This requires 'data' passed to this func to be the same as market_data used for feature gen
            # For Rapid Backtester, we essentially closure the feature_series
            aligned_feat = feature_series.reindex(data.index).fillna(0)

            if mode == 'trend':
                return aligned_feat.apply(np.sign) # 1 if >0, -1 if <0
            elif mode == 'mr':
                return -aligned_feat.apply(np.sign)
            return pd.Series(0, index=data.index)

        metrics = self.backtester.run(signal_logic, market_data)

        # Remove non-serializable equity curve
        if 'cumulative_returns' in metrics:
            del metrics['cumulative_returns']

        return metrics

    def _record_result(self, name: str, metrics: Dict):
        # In a real system we check if it exists first, or use upsert
        # For simplicity, we just add it.
        # Check if good enough?
        score = metrics.get('sharpe', 0)

        # Log everything or just decent ones?
        # Let's log if Sharpe > 0.0 to avoid spamming DB with trash
        if score > 0.0:
            hyp_id = self.manager.add_hypothesis(
                name=name,
                description=f"Auto-generated sweep hypothesis for {name}",
                code="<auto-generated>"
            )
            self.manager.update_metrics(hyp_id, metrics)
            logger.info(f"Discovered potential edge: {name} (Sharpe: {score:.2f})")
