
import json
import logging
from pathlib import Path

# Additional Tickers to ensure 500+ (S&P 500 + others)
ADDITIONAL_TICKERS = [
    "A", "AAL", "AAP", "AA", "AAON", "AAR", "AAWW", "AB", "ABB", "ABCB", "ABEO", "ABG",
    "ABM", "ABR", "AC", "ACA", "ACAD", "ACCD", "ACCO", "ACEL", "ACGL", "ACHC", "ACI", "ACIW",
    "ACLS", "ACM", "ACN", "ACST", "ACT", "ACVA", "ADBE", "ADC", "ADCT", "ADM", "ADNT",
    "ADP", "ADSK", "ADT", "ADUS", "ADV", "ADVM", "AEE", "AEG", "AEHR", "AEIS", "AEL",
    "AEM", "AEO", "AEP", "AER", "AES", "AFL", "AG", "AGCO", "AGEN", "AGI", "AGIO", "AGL",
    "AGM", "AGNC", "AGO", "AGR", "AGS", "AGX", "AGYS", "AHCO", "AHH", "AHT", "AI", "AIG",
    "AIMC", "AIN", "AIP", "AIR", "AIT", "AIV", "AIZ", "AJG", "AKAM", "AKR", "AKS", "AL",
    "ALB", "ALCO", "ALE", "ALG", "ALGM", "ALGN", "ALGT", "ALK", "ALL", "ALLE", "ALLY",
    "ALNY", "ALP", "ALRM", "ALSN", "ALT", "ALTR", "ALV", "ALX", "AM", "AMAT", "AMBA",
    "AMBC", "AMC", "AMCR", "AMCX", "AMD", "AME", "AMED", "AMG", "AMGN", "AMH", "AMKR",
    "AMLX", "AMN", "AMOT", "AMP", "AMPH", "AMPL", "AMR", "AMRC", "AMRX", "AMT", "AMTB",
    "AMWD", "AMZN", "AN", "ANET", "ANF", "ANGI", "ANIP", "ANNX", "ANSS", "ANTM", "AON",
    "AOS", "AOSL", "APA", "APAM", "APD", "APEI", "APG", "APH", "APLE", "APLS", "APO",
    "APP", "APPF", "APPN", "APPS", "APTV", "AR", "ARAY", "ARCB", "ARCH", "ARCO", "ARCT",
    "ARD", "ARE", "ARES", "ARGO", "ARI", "ARKR", "ARL", "ARLO", "ARMK", "ARNC", "AROC",
    "AROW", "ARR", "ARRY", "ARTNA", "ARW", "ARWR", "ASAN", "ASB", "ASGN", "ASH", "ASI",
    "ASIX", "ASML", "ASND", "ASO", "ASPN", "ASPS", "ASR", "ASTE", "ASTS", "ASUR", "ASX",
    "AT", "ATC", "ATCO", "ATGE", "ATH", "ATI", "ATKR", "ATLC", "ATLO", "ATMC", "ATMU",
    "ATO", "ATOM", "ATR", "ATRA", "ATRC", "ATRI", "ATRO", "ATSG", "ATUS", "ATVI", "ATXI",
    "AU", "AVA", "AVAV", "AVB", "AVD", "AVDL", "AVDX", "AVGO", "AVGR", "AVID", "AVIR",
    "AVNS", "AVNT", "AVNW", "AVP", "AVT", "AVTR", "AVY", "AVYA", "AWH", "AWI", "AWK",
    "AWR", "AX", "AXCCP", "AXL", "AXON", "AXP", "AXR", "AXS", "AXSM", "AXTA", "AXTI",
    "AY", "AYI", "AYX", "AZEK", "AZN", "AZO", "AZPN", "AZTA", "AZZ", "B", "BA", "BABA",
    "BAC", "BAH", "BALY", "BAM", "BANC", "BAND", "BANF", "BANR", "BATRA", "BATRK", "BAX",
    "BB", "BBBY", "BBCP", "BBD", "BBDC", "BBDO", "BBIO", "BBL", "BBN", "BBSI", "BBVA",
    "BBW", "BBY", "BC", "BCBP", "BCC", "BCE", "BCG", "BCH", "BCI", "BCLI", "BCML", "BCO",
    "BCOV", "BCPC", "BCRX", "BCS", "BCSF", "BCX", "BDC", "BDJ", "BDL", "BDN", "BDR",
    "BDRA", "BDSI", "BDX", "BE", "BEAM", "BECN", "BEDU", "BEKE", "BELFA", "BEN", "BEP",
    "BERY", "BEST", "BF.A", "BF.B", "BFAM", "BFIN", "BFST", "BG", "BGCP", "BGFV", "BGI",
    "BGNE", "BGR", "BGS", "BGSF", "BGY", "BH", "BHA", "BHB", "BHC", "BHE", "BHF", "BHLB",
    "BHP", "BHR", "BHT", "BHVN", "BIDU", "BIG", "BIIB", "BIL", "BILL", "BIO", "BIO.B",
    "BIOC", "BIOL", "BIOS", "BIOT", "BIOX", "BIP", "BIT", "BITF", "BIV", "BJ", "BJRI",
    "BK", "BKCC", "BKD", "BKE", "BKH", "BKI", "BKK", "BKN", "BKNG", "BKR", "BKS", "BKSC",
    "BKT", "BKU", "BKX", "BKYI", "BL", "BLBD", "BLCO", "BLD", "BLDE", "BLDR", "BLE",
    "BLFS", "BLI", "BLK", "BLKB", "BLL", "BLMN", "BLNK", "B", "BOX", "BP", "BPMC", "BPOP",
    "BPRN", "BR", "BRBR", "BRC", "BRCC", "BRDG", "BREW", "BRFS", "BRG", "BRID", "BRK.A",
    "BRK.B", "BRKL", "BRKR", "BRKS", "BRLI", "BRMK", "BRO", "BRP", "BRQS", "BRS", "BRT",
    "BRX", "BRY", "BSAC", "BSBR", "BSCN", "BSCO", "BSCP", "BSCQ", "BSCR", "BSCS", "BSCT",
    "BSD", "BSET", "BSGM", "BSIG", "BSL", "BSM", "BSMX", "BSQR", "BSRR", "BST", "BSTZ",
    "BSV", "BSX", "BSY", "BTAL", "BTB", "BTBT", "BTE", "BTG", "BTI", "BTN", "BTO", "BTT",
    "BTU", "BTZ", "BUD", "BUI", "BUR", "BURL", "BUSE", "BV", "BVN", "BVS", "BVXV", "BW",
    "BWA", "BWB", "BWEN", "BWFG", "BWL.A", "BWMX", "BWXT", "BX", "BXC", "BXMT", "BXP",
    "BXR", "BXS", "BY", "BYD", "BYFC", "BYND", "BZH", "C", "CAAP", "CABO", "CAC", "CACC",
    "CACI", "CADE", "CAE", "CAF", "CAG", "CAH", "CAI", "CAJ", "CAKE", "CAL", "CALM",
    "CALX", "CAMP", "CAMT", "CAN", "CANG", "CAPL", "CAPR", "CAR", "CARA", "CARE", "CARG",
    "CARR", "CARS", "CASA", "CASH", "CASI", "CASS", "CASY", "CAT", "CATC", "CATM", "CATO",
    "CATY", "CB", "CBAN", "CBAY", "CBB", "CBD", "CBIO", "CBK", "CBL", "CBMB", "CBMG",
    "CBNK", "CBOE", "CBRE", "CBRL", "CBSH", "CBT", "CBU", "CBZ", "CC", "CCB", "CCBG",
    "CC C", "CCD", "CCEP", "CCF", "CCI", "CCJ", "CCK", "CCL", "CCLP", "CCM", "CCMP",
    "CCNE", "CCO", "CCOI", "CCRN", "CCS", "CCSI", "CCTS", "CCU", "CCV", "CCXI", "CD",
    "CDAK", "CDAY", "CDC", "CDE", "CDEV", "CDK", "CDLX", "CDMO", "CDNA", "CDNS", "CDOR",
    "CDR", "CDRE", "CDS", "CDTX", "CDW", "CDXC", "CDXS", "CDZI", "CE", "CEA", "CECE",
    "CECO", "CEE", "CEG", "CEI", "CEIX", "CELC", "CELG", "CELH", "CEM", "CEMI", "CEN",
    "CENT", "CENTA", "CENX", "CEO", "CEPU", "CEQP", "CERE", "CERN", "CERS", "CERT", "CET",
    "CETX", "CEV", "CEVA", "CF", "CFB", "CFBK", "CFFI", "CFFN", "CFG", "CFIV", "CFLT",
    "CFMS", "CFO", "CFR", "CFRX", "CFX", "CG", "CGA", "CGBD", "CGC", "CGEN", "CGNX",
    "CGO", "CGW", "CH", "CHAP", "CHCT", "CHD", "CHDN", "CHE", "CHEF", "CHEK", "CHGG",
    "CHH", "CHI", "CHK", "CHKP", "CHKR", "CHMA", "CHMG", "CHMI", "CHNG", "CHNR", "CHPM",
    "CHRA", "CHRB", "CHRS", "CHRW", "CHS", "CHT", "CHTR", "CHUY", "CHW", "CHX", "CHY",
    "CI", "CIA", "CIB", "CIC", "CIEN", "CIF", "CIG", "CIGI", "CII", "CIK", "CIL", "CIM",
    "CINF", "CIO", "CIR", "CIT", "CIVB", "CIVI", "CIX", "CIXX", "CIZN", "CJ", "CKH",
    "CKPT", "CKX", "CL", "CLA", "CLAR", "CLB", "CLBK", "CLBS", "CLC", "CLCT", "CLD",
    "CLDR", "CLDT", "CLDX", "CLEU", "CLF", "CLFD", "CLGN", "CLH", "CLI", "CLIR", "CLL",
    "CLM", "CLMT", "CLNC", "CLNE", "CLNN", "CLNY", "CLOU", "CLOV", "CLPR", "CLPS", "CLR",
    "CLRB", "CLRO", "CLS", "CLSD", "CLSK", "CLSN", "CLV", "CLVT", "CLW", "CLX", "CLXT",
    "CM", "CMA", "CMBM", "CMC", "CMCL", "CMCM", "CMCO", "CMCSA", "CMCT", "CMD", "CME",
    "CMG", "CMI", "CMLS", "CMM", "CMO", "CMP", "CMPR", "CMPS", "CMRE", "CMRX", "CMS",
    "CMSA", "CMSC", "CMT", "CMTG", "CMTL", "CMU", "CNA", "CNBKA", "CNC", "CNCE", "CND",
    "CNDA", "CNDT", "CNET", "CNF", "CNFR", "CNH", "CNHI", "CNI", "CNK", "CNL", "CNM",
    "CNMD", "CNN", "CNNB", "CNO", "CNP", "CNQ", "CNR", "CNS", "CNSL", "CNSP", "CNST",
    "CNT", "CNTG", "CNTY", "CNX", "CNXC", "CNXM", "CNXN", "CO", "CODI", "CODX", "COE",
    "COF", "COFS", "COG", "COGT", "COHN", "COHR", "COHU", "COIN", "COKE", "COLB", "COLD",
    "COLL", "COLM", "COMM", "COMP", "COMS", "CONE", "CONN", "COO", "COOK", "COOL", "COOP",
    "COP", "COR", "CORE", "CORT", "CORZ", "COST", "COTY", "COUP", "COUR", "COW", "COWN",
    "CP", "CPA", "CPAC", "CPB", "CPE", "CPF", "CPG", "CPHC", "CPHI", "CPIX", "CPK",
    "CPLP", "CPNG", "CPRI", "CPRT", "CPRX", "CPS", "CPSH", "CPSI", "CPSS", "CPT", "CPZ",
    "CQP", "CR", "CRAI", "CRBP", "CRC", "CRCT", "CRD.A", "CRD.B", "CRDL", "CRDO", "CRE",
    "CREG", "CREX", "CRF", "CRH", "CRI", "CRIS", "CRK", "CRL", "CRM", "CRMD", "CRMT",
    "CRNC", "CRNT", "CROX", "CRS", "CRSP", "CRSR", "CRT", "CRTO", "CRTX", "CRUS", "CRVL",
    "CRVS", "CRWD", "CRWS", "CRY", "CRZ", "CS", "CSBR", "CSC", "CSCO", "CSGP", "CSGS",
    "CSII", "CSIQ", "CSL", "CSOD", "CSPI", "CSQ", "CSR", "CSSE", "CSTE", "CSTL", "CSTM",
    "CSTR", "CSWC", "CSWI", "CSX", "CTAS", "CTB", "CTBI", "CTC.A", "CTEK", "CTG", "CTGO",
    "CTHR", "CTIB", "CTIC", "CTKB", "CTLP", "CTLT", "CTMX", "CTO", "CTOS", "CTP", "CTRA",
    "CTRE", "CTRM", "CTRN", "CTS", "CTSH", "CTSO", "CTT", "CTVA", "CTXR", "CTXS", "CTY",
    "CUB", "CUBE", "CUBI", "CUE", "CUEN", "CUK", "CULP", "CURI", "CURO", "CURV", "CUTR",
    "CUZ", "CVBF", "CVCO", "CVCY", "CVE", "CVEO", "CVET", "CVGI", "CVGW", "CVI", "CVII",
    "CVLG", "CVLT", "CVLY", "CVM", "CVNA", "CVR", "CVS", "CVT", "CVU", "CVV", "CVX",
    "CW", "CWBC", "CWBR", "CWCO", "CWD", "CWEN", "CWEN.A", "CWH", "CWK", "CWST", "CWT",
    "CX", "CXDO", "CXE", "CXH", "CXM", "CXO", "CXP", "CXW", "CYAN", "CYB", "CYBE",
    "CYBR", "CYCC", "CYCN", "CYD", "CYH", "CYN", "CYRN", "CYRX", "CYT", "CYTK", "CYTO",
    "CYXT", "CZN", "CZR", "CZWI", "D", "DAC", "DAIO", "DAKT", "DAL", "DAN", "DAO",
    "DAR", "DARE", "DASH", "DATS", "DAVA", "DB", "DBD", "DBE", "DBI", "DBRG", "DBTX",
    "DBV", "DBX", "DC", "DCBO", "DCF", "DCI", "DCO", "DCOM", "DCP", "DCPH", "DCRB",
    "DCT", "DCTH", "DD", "DDD", "DDS", "DDT", "DE", "DEA", "DECK", "DEI", "DELL",
    "DEN", "DENN", "DEO", "DESP", "DEX", "DFH", "DFIN", "DFP", "DFS", "DG", "DGICA",
    "DGICB", "DGII", "DGLY", "DGX", "DH", "DHC", "DHI", "DHR", "DHT", "DHX", "DIA",
    "DIN", "DIOD", "DIS", "DISA", "DISH", "DIT", "DJCO", "DK", "DKL", "DKNG", "DKS",
    "DLA", "DLB", "DLHC", "DLNG", "DLPH", "DLR", "DLTH", "DLTR", "DLX", "DLY", "DM",
    "DMAC", "DMAQ", "DMB", "DMC", "DMCU", "DMF", "DMLP", "DMR", "DMS", "DMTK", "DMYI",
    "DMZQ", "DNA", "DNAY", "DNB", "DNLI", "DNMR", "DNN", "DNOW", "DNP", "DO", "DOC",
    "DOCN", "DOCS", "DOCU", "DOG", "DOGZ", "DOLE", "DOMA", "DOMO", "DOOO", "DOOR",
    "DORM", "DOV", "DOW", "DOX", "DPZ", "DQ", "DRD", "DRE", "DRH", "DRI", "DRIO",
    "DRMA", "DRNA", "DRQ", "DRRX", "DRTT", "DRUA", "DRV", "DRW", "DS", "DSGN", "DSGR",
    "DSGX", "DSKE", "DSL", "DSM", "DSP", "DSS", "DST", "DSU", "DSW", "DSX", "DT",
    "DTC", "DTE", "DTEA", "DTF", "DTI", "DTIL", "DTM", "DTOC", "DTP", "DTQ", "DTR",
    "DTST", "DUK", "DULA", "DULB", "DUOT", "DVA", "DVAX", "DVN", "DVP", "DWSN", "DX",
    "DXC", "DXCM", "DXF", "DXLG", "DXPE", "DXR", "DXYN", "DY", "DYAI", "DYNT", "DZSI",
    "E", "EA", "EAC", "EAF", "EAR", "EARN", "EAT", "EB", "EBAY", "EBC", "EBF", "EBIX",
    "EBS", "EBTC", "EC", "ECC", "ECL", "ECOL", "ECOM", "ECOR", "ECOW", "ECPG", "ECR",
    "ECT", "ECVT", "ED", "EDAP", "EDD", "EDF", "EDI", "EDIT", "EDN", "EDR", "EDRY",
    "EDU", "EDUC", "EE", "EEA", "EEFT", "EEX", "EFC", "EFOI", "EFR", "EFSC", "EFX",
    "EGAN", "EGBN", "EGF", "EGHT", "EGLE", "EGO", "EGOV", "EGP", "EGRX", "EGY", "EH",
    "EHC", "EHI", "EHT", "EHTH", "EIG", "EIGR", "EIX", "EKSO", "EL", "ELA", "ELAN",
    "ELAT", "ELC", "ELD", "ELF", "ELMD", "ELOX", "ELP", "ELS", "ELSE", "ELTK", "ELV",
    "ELY", "ELYS", "EMAN", "EMBC", "EMCF", "EME", "EMF", "EMKR", "EML", "EMN", "EMO",
    "EMP", "EMR", "EMX", "ENB", "ENBL", "ENDP", "ENFN", "ENG", "ENIA", "ENIC", "ENJ",
    "ENLC", "ENLV", "ENOB", "ENOV", "ENPH", "ENR", "ENS", "ENSG", "ENSV", "ENT",
    "ENTA", "ENTG", "ENTX", "ENV", "ENVA", "ENZ", "EOG", "EOI", "EOLS", "EOS", "EOT",
    "EP-C", "EPAC", "EPAM", "EPAY", "EPC", "EPD", "EPHY", "EPIX", "EPM", "EPR", "EPRT",
    "EPSN", "EPZM", "EQ", "EQBK", "EQC", "EQH", "EQIX", "EQNR", "EQR", "EQS", "EQT",
    "EQX", "ERF", "ERG", "ERH", "ERIC", "ERIE", "ERII", "ERJ", "EROS", "ES", "ESA",
    "ESBA", "ESCA", "ESE", "ESEA", "ESG", "ESGR", "ESGRO", "ESI", "ESLT", "ESM", "ESNT",
    "ESP", "ESPR", "ESQ", "ESRT", "ESS", "ESSA", "ESTA", "ESTC", "ESTE", "ET", "ETAO",
    "ETB", "ETD", "ETG", "ETH", "ETJ", "ETM", "ETN", "ETO", "ETON", "ETP", "ETR",
    "ETRN", "ETSY", "ETTX", "ETV", "ETW", "ETWO", "ETY", "EURN", "EVA", "EVBG", "EVC",
    "EVCM", "EVE", "EVER", "EVF", "EVG", "EVGN", "EVH", "EVI", "EVK", "EVLO", "EVLV",
    "EVM", "EVN", "EVO", "EVOK", "EVOL", "EVOP", "EVR", "EVRG", "EVRI", "EVT", "EVTC",
    "EVTL", "EW", "EWA", "EWBC", "EWC", "EWD", "EWFA", "EWFC", "EWJ", "EWL", "EWM",
    "EWN", "EWO", "EWP", "EWQ", "EWR", "EWS", "EWT", "EWU", "EWV", "EWW", "EWX", "EWY",
    "EWZ", "EXAS", "EXC", "EXD", "EXEL", "EXG", "EXK", "EXLS", "EXP", "EXPD", "EXPE",
    "EXPI", "EXPO", "EXPR", "EXR", "EXTN", "EXTR", "EYE", "EYEN", "EYES", "EYPT",
    "EZPW", "F", "FA", "FAA", "FAF", "FAIL", "FALN", "FAMI", "FANG", "FANH", "FARM",
    "FARO", "FAST", "FAT", "FATE", "FATP", "FAZ", "FB", "FBC", "FBHS", "FBIO", "FBIZ",
    "FBK", "FBL", "FBMS", "FBNC", "FBP", "FC", "FCA", "FCAL", "FCAP", "FBC", "FCBC",
    "FCCO", "FCCY", "FCE.A", "FCEL", "FCF", "FCFS", "FCN", "FCNCA", "FCO", "FCPT",
    "FCRD", "FCT", "FCX", "FDBC", "FDC", "FDEU", "FDL", "FDS", "FDT", "FDUS", "FDX",
    "FE", "FEIM", "FELE", "FEM", "FEN", "FENC", "FENG", "FEO", "FEP", "FET", "FF",
    "FFBC", "FFC", "FFG", "FFIC", "FFIN", "FFIV", "FFNW", "FFTY", "FG", "FGB", "FGBI",
    "FGEN", "FGF", "FGM", "FHN", "FHY", "FI", "FIBK", "FICO", "FIF", "FIG", "FII",
    "FIZZ", "FIS", "FISV", "FIT", "FITB", "FIVE", "FIVN", "FIX", "FIXX", "FIZZ",
    "FJP", "FKO", "FKU", "FL", "FLC", "FLDM", "FLEX", "FLGC", "FLGT", "FLIC", "FLIR",
    "FLL", "FLME", "FLMN", "FLN", "FLNG", "FLNT", "FLO", "FLOW", "FLR", "FLS", "FLT",
    "FLUX", "FLWS", "FLXN", "FLXS", "FLY", "FM", "FMAO", "FMB", "FMBH", "FMC", "FMD",
    "FMHI", "FMN", "FMNB", "FMO", "FMS", "FMT", "FMX", "FMY", "FN", "FNA", "FNB",
    "FNCB", "FND", "FNF", "FNGD", "FNGR", "FNGU", "FNKO", "FNLC", "FNV", "FNWB", "FOA",
    "FOCS", "FOF", "FOLD", "FONR", "FOR", "FORA", "FORD", "FORG", "FORM", "FORR",
    "FORTY", "FOSL", "FOX", "FOXA", "FOXF", "FPA", "FPAC", "FPAY", "FPC", "FPI",
    "FPL", "FPO", "FR", "FRA", "FRBA", "FRBK", "FRC", "FRD", "FREE", "FRG", "FRGA",
    "FRGI", "FRHC", "FRLN", "FRME", "FRO", "FRPH", "FRPT", "FRSX", "FRT", "FRWA",
    "FSB", "FSBC", "FSC", "FSCO", "FSD", "FSFG", "FSI", "FSK", "FSLR", "FSM", "FSMA",
    "FSP", "FSS", "FSTR", "FSV", "FSZ", "FT", "FTAA", "FTAI", "FTCH", "FTCI", "FTDR",
    "FTEK", "FTHM", "FTI", "FTK", "FTL", "FTNT", "FTR", "FTRE", "FTS", "FTSL", "FTSM",
    "FTSV", "FTV", "FUBO", "FUL", "FULC", "FULT", "FUN", "FUNC", "FUND", "FUSB", "FUSE",
    "FUTU", "FUV", "FV", "FVC", "FVCB", "FVRR", "FWONA", "FWONK", "FWRD", "FXC", "FXD",
    "FXE", "FXF", "FXI", "FXL", "FXN", "FXO", "FXP", "FXR", "FXZ", "FYBR", "G", "GABC",
    "GAIA", "GAIN", "GALT", "GAM", "GAMB", "GAME", "GATO", "GATX", "GB", "GBDC",
    "GBIO", "GBL", "GBLI", "GBT", "GBX", "GC=F", "GCBC", "GCI", "GCO", "GCP", "GD",
    "GDDY", "GDEN", "GDOT", "GDP", "GDRX", "GDS", "GDV", "GDX", "GDXJ", "GE", "GEF",
    "GEF.B", "GEG", "GEHC", "GEN", "GENE", "GENI", "GEO", "GEOS", "GERN", "GES", "GET",
    "GEVO", "GF", "GFA", "GFF", "GFI", "GFL", "GFLU", "GFS", "GG", "GGB", "GGG",
    "GGN", "GGT", "GGZ", "GH", "GHC", "GHG", "GHI", "GHM", "GHL", "GHRS", "GHY",
    "GI", "GIB", "GIC", "GIG", "GIGA", "GIGM", "GIII", "GILD", "GILT", "GIN", "GIPR",
    "GIRD", "GIS", "GK", "GKOS", "GL", "GLAD", "GLBE", "GLBS", "GLD", "GLDAM", "GLDD",
    "GLDI", "GLEO", "GLG", "GLI", "GLL", "GLNG", "GLO", "GLOB", "GLOP", "GLP", "GLPI",
    "GLQ", "GLRE", "GLS", "GLSI", "GLT", "GLTR", "GLU", "GLUE", "GLV", "GLW", "GLYC",
    "GM", "GME", "GMED", "GMRE", "GMS", "GMTX", "GNA", "GNAC", "GNE", "GNK", "GNL",
    "GNLN", "GNMA", "GNMS", "GNPX", "GNRC", "GNT", "GNTX", "GNTY", "GNUS", "GNW", "GO",
    "GOCO", "GODO", "GOG", "GOGL", "GOGO", "GOLF", "GOOD", "GOOG", "GOOGL", "GOP", "GORO",
    "GOSS", "GOTU", "GP", "GPC", "GPI", "GPK", "GPL", "GPM", "GPMT", "GPN", "GPOR",
    "GPP", "GPRE", "GPRO", "GPS", "GPX", "GQ", "GRA", "GRAM", "GRBK", "GRC", "GRDG",
    "GREEN", "GRES", "GRF", "GRI", "GRID", "GRIF", "GRIN", "GRMN", "GRN", "GRND", "GRNQ",
    "GRO", "GROW", "GRP.U", "GRPN", "GRTS", "GRUB", "GRWG", "GRX", "GS", "GSAH", "GSAT",
    "GSBC", "GSBD", "GSHD", "GSIT", "GSK", "GSL", "GSM", "GSOL", "GSP", "GSS", "GST",
    "GSV", "GSX", "GT", "GTBIF", "GTEC", "GTES", "GTH", "GTIM", "GTLS", "GTN", "GTN.A",
    "GTS", "GTX", "GTY", "GTYH", "GULF", "GURE", "GUT", "GV", "GVA", "GVP", "GWGH",
    "GWRE", "GWRS", "GWW", "GYC", "H", "HA", "HAE", "HAFC", "HAIN", "HAL", "HALL", "HALO",
    "HAPP", "HARP", "HAS", "HASI", "HAYN", "HAYW", "HB", "HBAN", "HBB", "HBCP", "HBI",
    "HBM", "HBMD", "HBNC", "HBP", "HBT", "HCA", "HCC", "HCCI", "HCDI", "HCE", "HCHC",
    "HCI", "HCKT", "HCM", "HCP", "HCR", "HCSIG", "HD", "HDB", "HDS", "HDSN", "HE",
    "HEAR", "HEC", "HEES", "HEI", "HEI.A", "HELE", "HEP", "HEPA", "HEQ", "HES", "HESM",
    "HFFG", "HFRO", "HFWA", "HGH", "HGLB", "HGSH", "HGV", "HHC", "HHS", "HI", "HIBB",
    "HIFS", "HIG", "HII", "HIL", "HIMS", "HIN", "HIPO", "HIPP", "HIW", "HIX", "HKIB",
    "HL", "HLA", "HLF", "HLG", "HLI", "HLIO", "HLIT", "HLMN", "HLNE", "HLX", "HMC",
    "HMG", "HMHC", "HMLP", "HMN", "HMNF", "HMPT", "HMST", "HMSY", "HMTV", "HMY", "HNAM",
    "HNDL", "HNGR", "HNI", "HNNA", "HNP", "HNRG", "HOFT", "HOFV", "HOG", "HOHI", "HOLI",
    "HOLL", "HOLX", "HOMB", "HOME", "HON", "HOOD", "HOOK", "HOPE", "HOTH", "HOV", "HOWL",
    "HP", "HPE", "HPF", "HPI", "HPK", "HPL", "HPP", "HPQ", "HPS", "HQH", "HQL", "HR",
    "HRB", "HRC", "HRI", "HRL", "HRMY", "HROW", "HRT", "HRTG", "HRTX", "HRZN", "HSBC",
    "HSC", "HSDT", "HSIC", "HSII", "HST", "HSTM", "HSY", "HT", "HTA", "HTBK", "HTD",
    "HTFA", "HTGC", "HTH", "HTHT", "HTLD", "HTLF", "HTZ", "HUBB", "HUBS", "HUD", "HUM",
    "HUN", "HURC", "HURN", "HUSA", "HUSN", "HVB", "HVT", "HVT.A", "HWBK", "HWC", "HWKN",
    "HWM", "HXL", "HY", "HYB", "HYD", "HYFM", "HYG", "HYI", "HYLN", "HYLS", "HYM", "HYMB",
    "HYT", "HYW", "HYZ", "HZNP", "HZO", "I", "I", "IA", "IAC", "IAG", "IAI", "IAK",
    "IAM", "IART", "IAT", "IBA", "IBB", "IBCP", "IBDR", "IBEX", "IBIO", "IBKR", "IBM",
    "IBN", "IBO", "IBOC", "IBP", "IBR", "IBTX", "ICAD", "ICBK", "ICCC", "ICCH", "ICD",
    "ICE", "ICFI", "ICHR", "ICL", "ICLR", "ICMB", "ICON", "ICPT", "ICUI", "ID", "IDA",
    "IDCC", "IDE", "IDEX", "IDN", "IDR", "IDRA", "IDT", "IDXX", "IDYA", "IE", "IEA",
    "IEC", "IEF", "IEP", "IESC", "IEX", "IFF", "IFGL", "IFIN", "IFN", "IFS", "IG",
    "IGA", "IGC", "IGD", "IGDS", "IGE", "IGF", "IGG", "IGI", "IGIC", "IGM", "IGMS",
    "IGN", "IGOV", "IGR", "IGT", "IGV", "IH", "IHD", "IHE", "IHF", "IHI", "IHRT",
    "IHS", "IHT", "IIF", "IIIN", "IIIV", "IIM", "IIN", "IIPR", "IIR", "IIT", "VI",
    "IIV", "IIVIP", "IJH", "IJJ", "IJK", "IJR", "IJS", "IJSC", "IJT", "IKBS", "IKG",
    "IKNX", "IKT", "ILMN", "ILPT", "IMAB"
]

def expand_universe():
    path = Path("configs/universe.json")
    if not path.exists():
        logging.error("configs/universe.json not found")
        return

    try:
        with open(path, "r") as f:
            data = json.load(f)

        current_tickers = set(data.get("active_tickers", []))
        logging.info(f"Current universe size: {len(current_tickers)}")

        # Merge
        new_tickers = current_tickers.union(set(ADDITIONAL_TICKERS))

        # Validation filter (basic)
        final_list = sorted([t for t in new_tickers if isinstance(t, str) and len(t) > 0])

        data["active_tickers"] = final_list
        data["description"] = f"Expanded Universe ({len(final_list)} Assets) - Automated Expansion"
        data["last_updated"] = str(logging.Formatter().converter(None)) # Just a timestamp

        with open(path, "w") as f:
            json.dump(data, f, indent=2)

        logging.info(f"Expanded universe to {len(final_list)} tickers.")
        print(f"Universe expanded to {len(final_list)} tickers.")

    except Exception as e:
        logging.error(f"Failed to expand universe: {e}")
        print(f"Error: {e}")

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    expand_universe()
